[tox]
envlist = py37, py38, py39, lint, type
isolated_build = True

[testenv]
deps =
    pytest
    pytest-cov
commands =
    pytest --cov=cubey {posargs:tests}

[testenv:lint]
deps =
    flake8
    black
    isort
commands =
    flake8 cubey tests
    black --check cubey tests
    isort --check-only --profile black cubey tests

[testenv:type]
deps =
    mypy
commands =
    mypy cubey

[flake8]
max-line-length = 88
extend-ignore = E203
exclude = .git,__pycache__,build,dist
