app:
  logLevel : "DEBUG"
  logFormat : "%(asctime)s - %(levelname)s - %(message)s"

  solverCMD : "./kociemba/solve"

  camera_FR_deviceName : "/dev/v4l/by-path/platform-3f980000.usb-usb-0:1.2:1.0-video-index0"
  camera_BL_deviceName : "/dev/v4l/by-path/platform-3f980000.usb-usb-0:1.4:1.0-video-index0"

  min_scramble_moves : 30
  max_scramble_moves : 30

cam:
  colorCenters: [
    {
      rgb: [147.0,147.0,147.0],
      radius: 30.0,
      code: "W"
    },
    {
      rgb: [231.0,95.0,30.0],
      radius: 60.0,
      code: "B"
    },
    {
      rgb: [0.0,0.0,255.0],
      radius: 110.0,
      code: "R"
    },
    {
      rgb: [0.0,133.0,217.0],
      radius: 30.0,
      code: "O"
    },
    {
      rgb: [53.0,176.0,176.0],
      radius: 30.0,
      code: "Y"
    },
    {
      rgb: [160.0,198.0,0.0],
      radius: 30.0,
      code: "G"
    }
  ]

  colorFaceMap: {
    O: "F",           # Orange facing front.
    W: "B",           # White facing bottom.
    Y: "T",           # Yellow facing top.
    B: "L",           # Blue facing left.
    G: "R",           # Green facing right.
    R: "B",           # Red facing back.
    X: "X"            # UNKNOWN.
  }

  frameWidth: 640
  frameHeight: 480
  fps: 15

  # I'd rather use a tuple for these, but that requires YAML gymnastics in config.
  colorSampleCoords: {
    "front": [
      [280, 30], [420, 30],
      [270, 190], [430, 190],
      [270, 410], [410, 410]
    ],
    "back": [
      [250, 10], [410, 10],
      [245, 190], [420, 190],
      [250, 400], [405, 400]
    ]
  }

  flipCamera: N
  flipCode: 1       # 0 = vertical flip, 1 for horizontal, -1 for both.


stepper:
  
  pincfg_v1: &pincfg_v1 {      # This is for the cubey v1 PCB board.
    disable: 25,         # fake news. remove this before comitting. 
    dir: 17,
    up: 18,
    right: 3,            # You may have to disable I2C to use this pin.
    front: 14,           # You may have to disable UART to use this pin
    down: 5,
    left: 4,
    back: 2              # You may have to disable I2C to use this pin.
  }

  pincfg_v2: &pincfg_v2 {      # cubey_v2 
    disable: 25,
    dir: 15,             # You may have to disable UART to use this pin
    up: 14,              # You may have to disable UART to use this pin
    right: 18,
    front: 21,
    down: 16,
    left: 20,
    back: 23
  }

  pins: *pincfg_v1
  rpm: 60
  steps_per_rev: 200
  move_delay: 0.05   # seconds to wait between cube moves.
  hertz: 4000       # pulses per second. Basically speed. Do not exceed 6000 Hz.
  step_factor: 8    # 1/8 microstepping
