app:
  logLevel : "INFO"
  logFormat : "%(asctime)s - %(levelname)s - %(message)s"

  solverCMD : "../kociemba/solve"

  min_scramble_moves : 20
  max_scramble_moves : 50

cam:
  warmup_delay_ms : 1000
  camera_deviceID : 0

  calibration : "default_calib.yaml"

  frameWidth: 640
  frameHeight: 480
  fps: 60

  sample_coords: [
      [300, 30], [440, 40],
      [270, 220], [440, 220],
      [270, 430], [420, 440]
    ]

  flipCamera: False
  flipCode: 1       # 0 = vertical flip, 1 for horizontal, -1 for both.


stepper:
  
  pincfg_v2: &pincfg_v2       # GPIO pin mapping to function.
    back: 2
    front: 3
    left: 22
    right: 10
    disable: 6
    down: 13
    up: 19
    dir: 26
  

  pins: *pincfg_v2
  rpm: 60
  steps_per_rev: 200
  move_delay: 0.01   # seconds to wait between cube moves.
  hertz: 2000       # pulses per second. Basically speed. Do not exceed 4000 Hz.
  step_factor: 8    # 1/8 microstepping
