app:
  log_level : "INFO"
  log_format : "%(asctime)s - %(levelname)s - %(message)s"

cam:
  warmup_frames : 30
  camera_deviceID : 0

  calibration : "default_calib.yaml"
  
  # When sampling (or scanning) a coordinate in the captured image, average the color from a square 
  # of twice this width / height in pixels.
  sample_aperture: 10 # 20x20 pixel square

  sample_coords: [
      [300, 30], [440, 40],
      [270, 220], [440, 220],
      [270, 430], [420, 440]
    ]

  flip_camera: False
  flip_code: 1       # 0 = vertical flip, 1 for horizontal, -1 for both.


stepper:

  pin_map: # GPIO pin mapping to function.
    back: 2
    front: 3
    left: 22
    right: 10
    disable: 6
    down: 13
    up: 19
    dir: 26

  steps_per_rev: 200
  move_delay: 0.01   # seconds to wait between cube moves.
  hertz: 2000       # pulses per second. Basically speed. Do not exceed 4000 Hz.
  step_factor: 8    # 1/8 microstepping
